config/routes.rb
Rails.application.routes.draw do

  resources 'invitations'

  get 'callback/venmo'
  post 'callback/venmo'
  get 'callback/paypal'
  post 'callback/paypal'
  get 'callback/paypal_auth'
  post 'callback/paypal_auth'
  get 'callback/paypal_cancel'
  get 'callback/paypal_return'

  namespace :admin do
    resources :email_addresses
  end

  resources :messages

  get 'common/hot'
  get 'hot'=>'common#hot'
  get 'common/featured'
  get 'featured'=>'common#featured'
  get 'common/sponsored'
  get 'sponsored'=>'common#sponsored'
  get 'common/donate'
  get 'donate'=>'common#donate'

  resources :comments

  root 'static_pages#root'
  get 'coming_soon'=>'static_pages#coming_soon'
  post 'coming_soon'=>'static_pages#coming_soon'

  get 'toc'=>'static_pages#toc'
  get 'tos'=>'static_pages#tos'
  get 'faq'=>'static_pages#faq'
  get 'privacy'=>'static_pages#privacy'
  get 'about'=>'static_pages#about'
  get 'admin'=>'static_pages#admin'
  get 'venmo_declined'=>"static_pages#venmo_declined"
  get 'paypal_declined'=>"static_pages#paypal_declined"
  vendor = Rails.application.config.payment_vendor || 'paypal'
  get 'vendor_declined'=>"static_pages##{vendor}_declined"

  namespace :admin do
    resources :users
    resources :transfers
  end

  namespace :friends do
    get :add
    post :add
    post :remove
  end

  resources :users do
    member do
      get 'dashboard'
      post 'dashboard'
      post 'dashboard_transfer_list'
      get 'pending_validation'
      get 'resend_validation'
      get 'new_validation'
      patch 'update_password'
      get 'change_password'
      get 'friends'
      get 'close_account'
    end
    collection do
      get 'validate'
      get 'forgot_password'
      post 'temp_password'
    end
  end

  resources :transfers do
    member do
      post 'accept'
      post 'cancel'
      post 'complete'
      post 'fail'
      post 'off_dashboard'
    end
    collection do
      get 'recent'
    end
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'sessions/impersonate'

end

app/models/admin/user.rb
class Admin::User < User
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :first_name, :presence=>true
  validates :last_name, :presence=>true
  validates :email, :presence=>true, :uniqueness=>true
  validates :credentials, :presence=>true
  # email uniqueness

  has_many :credentials, :inverse_of=>:user, :dependent=>:destroy
  has_many :transfers, :inverse_of=>:user, :dependent=>:destroy
  has_many(:received_transfers,
           :foreign_key=>:recipient_id,
           :class_name=>"Transfer",
           :inverse_of=>:recipient,
           :dependent=>:destroy)
  has_many :comments
  has_one :validation
  has_many :user_friends
  has_many :friends, :through=>:user_friends
  has_many :messages
  has_many :venmo_users
  has_many :paypal_users
  has_many :invitations

  after_create :create_validation

  # Credentials
  accepts_nested_attributes_for :credentials

  def password_credential
    credentials.where.not(:encrypted_password=>nil).first
  end

  def credential_type_list
    credentials.map{|c| c.type_name}.join(", ").html_safe
  end

  def credentials_ok? *opts
    if opts && opts.last.is_a?(Hash)
      if opts.last[:password]
        password_credential.authenticate? opts.last[:password]
      end
    end
  end

  def signin session
    session[:user_id] = id
    session[:is_admin] = is_admin
    session[:pending] = self.validation(true) ? true : false
  end

  # Avatar
  has_attached_file(:avatar,
                    :styles=>{:medium=>"200x200>", :thumb=>"80x80>"},
                    :path=>"/users/avatars/:id_:basename.:style.:extension",
                    :default_url=>":style/missing-avatar.png")
  validates_attachment_content_type :avatar, :content_type=>/\Aimage\/.*\Z/

  # temporary password
  def create_temporary_password
    password = BCrypt::Engine.generate_salt[10..25]
    credentials.each do |credential|
      if credential.type_name == 'password'
        credential.delete
        credentials.create(:password=>password,
                           :temporary=>true,
                           :expires_at=>Time.now + 2.days)
        return password
      end
    end
    # you will need to login some otherway
    []  # alternate credentials
  end

  # Helpers
  def full_name
    "#{first_name} #{last_name}"
  end

  def current_password
  end

  def membership_time_str
    td = Time.now - created_at
    ActionController::Base.helpers.distance_of_time_in_words td
  end

  def descriptor
    full_name
  end

  def activity
    s = Transfer.new.user_completed!.recipient_completed!.state
    r = g = 0
    r += Transfer.where(:state=>s,
                        :recipient_id=>self.id,
                        :kind=>Transfer::NORMAL_KINDS).sum(:amount_cents)
    r += Transfer.where(:state=>s,
                        :user_id=>self.id,
                        :kind=>Transfer::REVERSE_KINDS).sum(:amount_cents)
    g += Transfer.where(:state=>s,
                        :user_id=>self.id,
                        :kind=>Transfer::NORMAL_KINDS).sum(:amount_cents)
    g += Transfer.where(:state=>s,
                        :recipient_id=>self.id,
                        :kind=>Transfer::REVERSE_KINDS).sum(:amount_cents)
    {:receive=>r/100.0,:give=>g/100.0}
  end

  def is_friend? other
    self.user_friends.where(:friend_id=>other.id).exists?
  end

  def venmo
    venmo_users.first
  end

  def venmo_active?
    v = venmo
    (v && v.active?) || false
  end

  def paypal
    paypal_users.first
  end

  def paypal_active?
    v = paypal
    (v && v.active?) || false
  end

  def can_receive_money?
    vendor = Rails.application.config.payment_vendor
    case vendor
    when :venmo
      v = venmo
      (v && v.can_receive_money?) || false
    when :paypal
      v = paypal
      (v && v.can_receive_money?) || false
    else
      true
    end
  end

  def can_transfer_money?
    vendor = Rails.application.config.payment_vendor
    case vendor
    when :venmo
      v = venmo
      (v && v.active? && !v.declined?) || false
    when :paypal
      v = paypal
      (v && v.active? && !v.declined?) || false
    else
      true
    end
  end

  def has_payments_for_approval?
    payments_for_approval_query.each do |p|
      return true if p.transfer.payment_source_user_id == id
    end
    false
  end
  def payments_for_approval
      payments_for_approval_query.
      to_a.
      delete_if {|p| p.transfer.payment_source_user_id != id}
  end
  def payments_for_approval_query
    Payment::Payment.
      pending_approval.
      joins(:transfer).
      includes(:transfer).
      where(["(transfers.user_id = ? OR transfers.recipient_id = ?)", id, id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = paged_search Admin::User
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = Admin::User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = Admin::User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.
        require(:admin_user).
        permit(:first_name,
               :last_name,
               :email,
               :time_zone,
               :is_admin,
               :avatar,
               :credentials_attributes=>[:password, :password_confirmation])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_validation, :except=>[:new,
                                             :create,
                                             :pending_validation,
                                             :resend_validation,
                                             :validate,
                                             :forgot_password,
                                             :temp_password]
  before_action :ensure_paypal, :except=>[:new,
                                       :create,
                                       :pending_validation,
                                       :resend_validation,
                                       :validate,
                                       :forgot_password,
                                       :temp_password]
  before_action :set_user, only: [:show, :edit, :update,
                                  :dashboard, :dashboard_transfer_list,
                                  :friends,
                                  :pending_validation,
                                  :resend_validation,
                                  :update_password,
                                  :change_password]
  before_action :ensure_correct_user, :only=>[:edit, :update,
                                              :dashboard,
                                              :friends,
                                              :dashboard_transfer_list]
  before_action(:check_temporary_password,
                :except=>[:change_password,
                          :new,
                          :create,
                          :pending_validation,
                          :resend_validation,
                          :validate,
                          :forgot_password,
                          :update_password,
                          :temp_password])


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    render :layout=>"layouts/common"
  end

  # GET /users/new
  def new
    @user = User.new
    session[:invitation_key] = params[:key] if params[:key]
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        if session[:invitation_key]
          invitation = Invitation.where(:key=>session[:invitation_key]).first
          if invitation
            invitation.update_attribute(:signup_id, @user.id)
          end
        end
        session.clear
        @user.signin session
        UserMailer.validation(@user).deliver
        format.html { redirect_to dashboard_user_path(@user), notice: 'Welcome to Buck Up!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(@user,
                                  notice: 'Your profile has been updated.') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_password
    @ok = false
    if @user.password_credential.authenticate? params[:user][:current_password]
      User.transaction do
        @user.password_credential.destroy!
        @credential = @user.credentials.create(password_params)
        if @credential.persisted?
          @notice = "Password changed"
          @ok = true
        else
          @notice = @credential.errors.values.join("<br/>").html_safe
          raise ActiveRecord::Rollback
        end
      end
    else
      @notice = "Current password does not match, try again"
    end
  end

  def change_password
  end

  def dashboard
    transfer_params = flash[:transfer]
    if transfer_params
      # load params for failed
      transfer_params = Marshal.load(transfer_params)
      em = transfer_params.delete :error_messages
      @transfer = Transfer.new transfer_params
      em.each { |k,v| @transfer.errors.add k,v }
    end
    render :layout=>"layouts/common"
  end

  def friends
    render :layout=>"layouts/common"
  end

  def dashboard_transfer_list
    @transfers = Transfer.
      involving(@user).
      where(:on_dashboard=>true).
      where(["comment_at > ?", Time.zone.parse(params[:timestamp])]).
      order(:created_at)
    respond_to do |format|
      format.js
    end
  end

  def pending_validation
  end

  def resend_validation
    raise "expecting validation" unless @user.validation
    UserMailer.validation(@user).deliver
  end

  def new_validation
    @user.validation.delete
    @user.create_validation
    UserMailer.validation(@user).deliver
    redirect_to pending_validation_path(@user)
  end

  def validate
    @validation = Validation.find_by(:key=>params[:key])
    if @validation
      @user = @validation.user
      if Time.now < @validation.expires_at
        @validation.delete
        session.clear
        @user.signin session
        redirect_to dashboard_user_path(@user)
      end
    else
      redirect_to login_path
    end
  end

  def forgot_password
  end

  def temp_password
    @user = User.find_by(:email=>params[:email])
    if @user
      password = @user.create_temporary_password
      UserMailer.temp_password(@user, password).deliver
    else
      flash[:notice] = "Your email does not match an existing user."
      redirect_to forgot_password_users_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.
        require(:user).
        permit(:first_name,
               :last_name,
               :email,
               :time_zone,
               :avatar,
               :credentials_attributes=>[:password, :password_confirmation])
    end
    def password_params
      params.
        require(:user).
        require(:credentials_attributes).
        require("0").
        permit(:password, :password_confirmation)
    end

    def ensure_correct_user
      unless @user.id == session[:user_id]
        redirect_to user_path(session[:user_id])
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_fields user
    out = show_field user, [:first_name, :last_name, :email]
    out << show_field(user, :is_admin) if @admin_page
    out << show_field(user, [:time_zone, :created_at])
    out << show_field(user, :invitations, invitation_list(user.invitations))
  end

  def user_edit_fields form
    time_zones = ActiveSupport::TimeZone.us_zones.map{|x| x.name}
    if @admin_page
      out = edit_field form, [:first_name, :last_name, :email]
      out << edit_field(form,
                        :time_zone,
                        :format=>:select,
                        :select_options=>time_zones)
      out << edit_field(form, :is_admin, :format=>:check_box)
      avatar_label =
        params[:action] == "edit" ? "Update Picture" : "Upload Picture"
      out << edit_field(form,
                        :avatar,
                        :placeholder=>avatar_label,
                        :format=>:file_field)
    else
      out = edit_field_simple form, [:first_name, :last_name, :email]
      out << edit_field_simple(form,
                        :time_zone,
                        :format=>:select,
                        :select_options=>time_zones)
      avatar_label =
        params[:action] == "edit" ?
        "Update Your Picture" : "Upload Your Picture"
      out << edit_field_simple(form,
                        :avatar,
                        :placeholder=>avatar_label,
                        :format=>:file_field)
    end
  end

  def password_credential_edit_fields form
    user = form.object
    credential = user.password_credential || user.credentials.build
    form.fields_for :credentials, credential do |cf|
      if @admin_page
        edit_field cf, [:password, :password_confirmation]
      else
        edit_field_simple cf, [:password, :password_confirmation]
      end
    end
  end

  def show_avatar user, size=:medium, *opts
    options = {:class=>"img-responsive"}
    options.merge! opts.last if opts && opts.last && opts.last.is_a?(Hash)
    image_tag user.avatar.url(size), options
  end
end

app/views/users/_avatar.html.erb
<div>
  <%=link_to show_avatar(user, :medium, :class=>"img-responsive"), user_path(user), :method=>:get%>
</div>
<% activity = user.activity %>
<div class="activity">
  <% if true || session[:user_id] != user.id %>
    <h4><%= user.full_name%></h4>
  <% end %>
  <span class="receive">$<%=activity[:receive].to_i%></span>
  &nbsp;
  <span class="give">$<%=activity[:give].to_i%></span>
</div>

app/views/users/_comment_list.html.erb
<% transfer.comments.each do |comment| %>
  <hr>
  <%= render :partial=>"comments/comment", :locals=>{:comment=>comment}%>
<% end %>
<button class="btn btn-default btn-info" data-toggle="modal" data-target="#comment_modal">
  Add Comment
</button>

app/views/users/_find_profile_form.html.erb
<%=form_tag "/users/#", :method=>:get, :id=>"find-profile" do%>
<% q = User %>
<% q = q.where.not(:id=>except) if defined? :except %>
<%=select_tag(:id,
	      options_from_collection_for_select(q.all,
						 :id,
						 :full_name),
	      :class=>"selectpicker",
              :data=>{
              :size=>10,
              :width=>'100%',
              'live-search'=>'true'
              }) %>
<%= submit_tag "View Profile", :class=>"btn btn-info form-control"%>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  <% label = /new|create/ =~ params[:action] ? "Sign Up!" : "Update Profile"%>
  <%= edit_fields form, :label=>label, :html=>{:multipart=>true} do %>
    <%=user_edit_fields form %>
    <% if params[:action] == "new" || params[:action] == "create" %>
      <%=password_credential_edit_fields form %>
    <% end %>
    <% if @user.errors.size > 0 %>
      <div class="well error-message well-sm">
      <ul>
      <% @user.errors.each do |field, msg|%>
	<% if "credentials".in?(field.to_s) %>
	  <li><%=msg%></li>
	<% end %>
      <% end %>
      </ul>
      </div>
    <% end %>
    <% if params[:action] == "new" || params[:action] == "create"%>
      <div class="signup-agreement">
	<p>By clicking the "Sign Up!" button below:</p>
	<ul>
	  <li>
	    you affirm that you are at least 18 years old and
	    reside in the United States,
	  </li>
	  <li>
	    you agree to the site's <%=link_to "Terms of Service", tos_path%>,
	  </li>
	  <li>
	    and you have read the <%=link_to "Privacy Notice", privacy_path%>.
	</ul>
      </div>
      <% elsif params[:action] == "edit" || params[:action] == "update"%>
      <div class="close-account-link"><%=link_to "Close Your Account",
      close_account_user_path(@current_user) %>
      </div>
      <div class=row>
	<%=cancel_profile_button%>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/_send_modal.html.erb
<div class="modal fade" id="send_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidd
en="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">???</h4>
      </div>
      <%= render "transfers/_form" %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_transfer.html.erb
<%= form_for(@user.transfers.build) do |form| %>
  <%= edit_fields form, :label=>"Send Money" do %>
    <%=transfer_edit_fields form %>
  <% end %>
<% end %>

app/views/users/_transfer_form.html.erb
<% t = @transfer || @user.transfers.build %>
<%= form_for(t) do |form| %>
  <%= edit_fields form, :label=>"Send Money" do %>
    <%=transfer_edit_fields form %>
  <% end %>
<% end %>

app/views/users/change_password.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
  <div id="password_form">
    <h1>Change Password</h1>

    <p>A new password was sent to you by email to your account on record.
      Please enter that password as 'Current Password' before setting your
      new password.</p>

    <div class="row">
      <%= form_for @user, :url=>update_password_user_path(@user),:remote=>true do |form| %>
	<%= hidden_field_tag :source, "change_password"%>
	<%= edit_fields form, :label=>"Change Password" do %>
	  <%= edit_field_simple(form, :current_password, :format=>:password_field) %>
	  <%=password_credential_edit_fields form %>
	<% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
  <div class=row>
    <%= render 'form' %>
  </div>
  <div class=row>
    <%= render 'password_form'%>
  </div>
</div>

app/views/users/friends.html.erb
<%= render :partial=>"find_profile_form", :locals=>{:except=>@user.id}%>
<div class="friends-list">
<% count = 0 %>
<% k = 2 %>
<% @user.friends.each do |friend| %>
  <% if count % k == 0 %>
    <div class="row">
  <% end %>
  <div class="col-sm-<%=12/k%> friend-list">
    <%= render :partial=>"users/avatar", :locals=>{:user=>friend}%>
    <%= send_bucks_button friend%>
  </div>
  <% if count % k == k - 1 %>
    </div>
  <% end %>
  <% count += 1 %>
<% end %>
</div>
<% @transfer = @user.transfers.build %>
<%= render "transfers/send_modal"%>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= sed_buttons user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= new_button User %>

app/views/users/pending_validation.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 dashboard">
<h1>Welcome to Bet U A Buck</h1>
<p>
  We have sent a validation mesage to your email account <%=@user.email%>.
  Please open the email and click on the link provided. If you do not
  see an email from us, check your spam folder.
</p>
<%= link_to "Resend", resend_validation_user_path(@user), :class=>"btn btn-info" %>
<% unless @user.paypal %>
<br>
<p>
  Bet U A Buck uses PayPal for payment processing. Please signup for an account
  at your earliest convienence.
</p>
<%= paypal_button @user %>
</p>
<% end %>
</div>

app/views/users/show.html.erb
<div class=row>
  Member for <%=@user.membership_time_str%>
</div>
<%= form_tag friends_add_path, :remote=>true, :id=>:friend_cb_form do %>
<%=hidden_field_tag :id, @user.id %>
<div class=row>
  Friend <%=check_box_tag :cb, "cb", @current_user.is_friend?(@user), :class=>"" %>
</div>
<% end %>
<% if @user.id == session[:user_id] %>
  <div class=row>
    <%= edit_profile_button @user %>
  </div>
<% end %>

<div class=row>
  <%= render :partial=>"transfer_list"%>
</div>

app/views/users/update_password.js.erb
payload = "<div class='well'><%=@notice%></div>"
<% if @ok -%>
click_tgt = $("#password_form > a")
if (click_tgt.size()>0) {
  click_tgt.click()
}
$("#password_form input[type=password]").each(function(idx,elem){
  $(elem).val("")
})
<% end -%>
tgt = $("#password_form .well")
if (tgt.size() == 0) {
  $("#password_form").append(payload)
} else {
  tgt.replaceWith(payload)
}

<% if @ok && params[:source]=="change_password" -%>
$("#password_form input[type=password]").each(function(idx,elem){
  $(elem).attr("disabled", "disabled")
})
$("#password_form input[type=submit]").attr("disabled", "disabled")
<% path = escape_javascript dashboard_user_path(@user)-%>
setTimeout(function(){window.location="<%=path%>"}, 3000)
<% end -%>