config/routes.rb
Rails.application.routes.draw do

  resources 'invitations'

  get 'callback/venmo'
  post 'callback/venmo'
  get 'callback/paypal'
  post 'callback/paypal'
  get 'callback/paypal_auth'
  post 'callback/paypal_auth'
  get 'callback/paypal_cancel'
  get 'callback/paypal_return'

  namespace :admin do
    resources :email_addresses
  end

  resources :messages

  get 'common/hot'
  get 'hot'=>'common#hot'
  get 'common/featured'
  get 'featured'=>'common#featured'
  get 'common/sponsored'
  get 'sponsored'=>'common#sponsored'
  get 'common/donate'
  get 'donate'=>'common#donate'

  resources :comments

  root 'static_pages#root'
  get 'coming_soon'=>'static_pages#coming_soon'
  post 'coming_soon'=>'static_pages#coming_soon'

  get 'toc'=>'static_pages#toc'
  get 'tos'=>'static_pages#tos'
  get 'faq'=>'static_pages#faq'
  get 'privacy'=>'static_pages#privacy'
  get 'about'=>'static_pages#about'
  get 'admin'=>'static_pages#admin'
  get 'venmo_declined'=>"static_pages#venmo_declined"
  get 'paypal_declined'=>"static_pages#paypal_declined"
  vendor = Rails.application.config.payment_vendor || 'paypal'
  get 'vendor_declined'=>"static_pages##{vendor}_declined"

  namespace :admin do
    resources :users
    resources :transfers
  end

  namespace :friends do
    get :add
    post :add
    post :remove
  end

  resources :users do
    member do
      get 'dashboard'
      post 'dashboard'
      post 'dashboard_transfer_list'
      get 'pending_validation'
      get 'resend_validation'
      get 'new_validation'
      patch 'update_password'
      get 'change_password'
      get 'friends'
      get 'close_account'
    end
    collection do
      get 'validate'
      get 'forgot_password'
      post 'temp_password'
    end
  end

  resources :transfers do
    member do
      post 'accept'
      post 'cancel'
      post 'complete'
      post 'fail'
      post 'off_dashboard'
    end
    collection do
      get 'recent'
    end
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'sessions/impersonate'

end

app/models/admin/transfer.rb
class Admin::Transfer < Transfer
end

app/controllers/admin/transfers_controller.rb
class Admin::TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    t = Admin::Transfer.joins(:user, :recipient).includes(:user, :recipient)
    @transfers = paged_search t
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Admin::Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Admin::Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to admin_transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Admin::Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.
        require(:admin_transfer).
        permit(:user_id, :recipient_id, :amount, :note, :kind, :user_state, :recipient_state, :image)
    end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :check_validation
  before_action(:set_transfer,
                only: [:show, :edit, :update, :destroy,
                       :off_dashboard])

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/recent
  # GET /transfers/recent.json
  def recent
    @transfers = Transfer.recent
    @user = User.find(session[:user_id])
    render :layout=>"layouts/common"
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    unless @current_user.can_transfer_money?
      redirect_to vendor_declined_path
      return
    end

    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        @transfer.initiate_payment
        notice = "Money sent to #{@transfer.recipient.first_name}"
        format.html { redirect_to(dashboard_user_path(@transfer.user),
                                  :notice=>notice)}
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html do
          a = @transfer.attributes
          a[:error_messages] = @transfer.errors.messages
          flash[:transfer] = Marshal.dump(a)
          redirect_to dashboard_user_path(@transfer.user_id)
        end
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def off_dashboard
    @transfer.update_attribute(:on_dashboard, false)
    respond_to do |format|
      format.html { redirect_to dashboard_user_path(@current_user) }
      format.js
    end
  end

  def complete
    state_change do
      @transfer.update_complete session[:user_id]
    end
  end

  def accept
    state_change do
      @transfer.update_accept session[:user_id]
    end
  end

  def cancel
    state_change do
      @transfer.update_cancel session[:user_id]
    end
  end

  def fail
    state_change do
      @transfer.update_fail session[:user_id]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.
        require(:transfer).
        permit(:user_id, :recipient_id, :amount, :note, :kind, :state, :image)
    end

  def state_change
    Transfer.transaction do
      @transfer = Transfer.find(params[:id])
      yield
    end
    respond_to do |format|
      format.html { redirect_to dashboard_user_path(@current_user) }
      format.js { render :update }
    end
  end

end

app/helpers/transfers_helper.rb
module TransfersHelper
  def transfer_fields transfer
    user = transfer.user
    out = show_field transfer, [:user_id, :recipient_id]
    out << show_field(transfer, :amount, number_to_currency(transfer.amount))
    out << show_field(transfer,
                      :created_at,
                      transfer.created_at_tz)
    out << show_field(transfer,
                      :updated_at,
                      transfer.updated_at)
    out << show_field(transfer,
                      :comments,
                      transfer.comments.count)
    out << show_field(transfer,
                      :comment_at,
                      transfer.comment_at)
    out << show_field(transfer, :note)
    out << show_field(transfer, :kind, transfer.kind_str)
    out << show_field(transfer, :state, transfer.state_str)
    if transfer.image.exists?
      out << show_field(transfer,
                        :image_x,
                        image_tag(transfer.image.url(:medium)))
    end
    out
  end

  def transfer_edit_fields form, *opts
    options = {}
    options.merge! opts.last if opts && opts.last.is_a?(Hash)
    if @admin_page
      out = edit_field form, [:user_id, :recipient_id, :amount, :note]
      image_label =
        params[:action] == "edit" ? "Update Picture" : "Upload Picture"
      out << edit_field(form,
                        :image,
                        :placeholder=>image_label,
                        :format=>:file_field)
      out << edit_field(form,
                        :kind,
                        :format=>:select,
                        :select_options=>Transfer.kind_options)
      out << edit_field(form,
                        :user_state,
                        :format=>:select,
                        :select_options=>Transfer.user_state_options)
      out << edit_field(form,
                        :recipient_state,
                        :format=>:select,
                        :select_options=>Transfer.recipient_state_options)
    else
      transfer_amounts =
        [1,2,3,4,5].map{|v| [number_to_currency(v), v]}
      out = form.hidden_field(:user_id)
      transfer = form.object
      query = User.where.not(:id=>transfer.user_id)
      query = query.includes(:paypal_users).all.to_a.
        delete_if{|x| !x.can_receive_money? }
      out << edit_field_simple(form,
                               :kind,
                               :format=>:select,
                               :select_options=>Transfer.kind_options)
      if options[:fixed_recipient]
        out << form.hidden_field(:recipient_id)
        name = transfer.recipient_id ? transfer.recipient.full_name : ""
        out << content_tag(:p, name , :class=>"form-control-static")
      else
        out << edit_field_simple(form,
                                 :recipient_id,
                                 :format=>:collection_select,
                                 :collection=>[query,
                                               :id,
                                               :full_name],
                                 :options=>{:prompt=>"Recipient?"},
                                 :class=>"selectpicker",
                                 :data=>{
                                   :size=>10,
                                   :width=>'100%',
                                   'live-search'=>'true'
                                 })
      end
      out << edit_field_simple(form,
                               :amount,
                               :format=>:select,
                               :select_value=>(transfer.amount || 1).to_i,
                               :select_options=>transfer_amounts)
      out << edit_field_simple(form, :note, :placeholder=>"For?")
      image_label =
        params[:action] == "edit" ? "Update Picture" : "Upload Picture"
      out << edit_field(form,
                        :image,
                        :placeholder=>image_label,
                        :format=>:file_field)
    end
  end

  COLOR_OUT = "bg-danger"
  COLOR_IN = "bg-success"
  COLOR_ACK = "bg-warning"
  COLOR_BET = "bg-info"
  COLOR_CANCEL = "bg-cancel"

  def completed_color transfer
    if transfer.user_id == session[:user_id]
      COLOR_OUT
    else
      COLOR_IN
    end
  end

  def completed_color_reverse transfer
    if transfer.user_id == session[:user_id]
      COLOR_IN
    else
      COLOR_OUT
    end
  end

  def transfer_color transfer
    return COLOR_CANCEL if transfer.canceled?
    return COLOR_ACK if transfer.pending? || transfer.recipient_pending_accept?
    if transfer.is_request?
      completed_color_reverse transfer
    elsif transfer.is_pending_bet? || transfer.is_pending_pledge?
      COLOR_BET
    elsif transfer.is_failed_bet?
      completed_color_reverse transfer
    else
      completed_color transfer
    end
  end

  def transfer_ack_actions transfer
    out = cancel_transfer_button(transfer)
    if transfer.recipient_id == session[:user_id]
      out = accept_transfer_button(transfer) + out
    end
    out
  end

  def ta_message msg
    content_tag(:div, msg, :class=>"message")
  end

  CANCEL_MSG = "Your cancel request is pending."
  FAIL_MSG = "Your failure request is pending."
  COMPLETE_MSG = "Your completion request is pending."

  def transfer_actions transfer
    return if transfer.completed?
    return if transfer.canceled?

    content_tag(:div,:class=>"transfer-actions") do
      if transfer.is_pay? || transfer.is_request?
        transfer_ack_actions transfer
      elsif transfer.is_bet? || transfer.is_pledge?
        out = []
        name = transfer.user.first_name
        #puts "#{transfer.inspect} == #{session[:user_id]}"
        if transfer.recipient_id == session[:user_id]
          if transfer.user_canceled?
            out << ta_message("#{name} wants to cancel.".html_safe)
            #out << reject_cancel_transfer_button(transfer)
            out << cancel_transfer_button(transfer)
          elsif transfer.recipient_canceled?
            out << ta_message(CANCEL_MSG)
          else
            out << cancel_transfer_button(transfer)
          end
          if transfer.recipient_pending_accept?
            out << accept_transfer_button(transfer)
          else
            if transfer.user_failed?
              msg = "#{name} says you failed. Click 'Fail' if you aggree"
              out.unshift ta_message(msg)
            end
            if transfer.recipient_failed?
              out.unshift ta_message(FAIL_MSG)
            else
              out << fail_transfer_button(transfer)
            end
            if transfer.user_completed?
              msg = "#{name} says you completed. Click 'OK' if you aggree"
              out.unshift ta_message(msg)
            end
            if transfer.recipient_completed?
              out.unshift ta_message(COMPLETE_MSG)
            else
              out << ok_transfer_button(transfer)
            end
          end
        elsif transfer.user_id == session[:user_id]
          if transfer.recipient_canceled?
            name = transfer.recipient.first_name
            out << ta_message("#{name} wants to cancel.".html_safe)
            #out << reject_cancel_transfer_button(transfer)
            out << cancel_transfer_button(transfer)
          elsif transfer.user_canceled?
            out << ta_message(CANCEL_MSG)
          else
            out << cancel_transfer_button(transfer)
          end
          if transfer.user_pending_accept?
            out << accept_transfer_button(transfer)
          else
            if transfer.recipient_failed?
              msg = "#{name} admits failure. Click 'Fail' if you aggree"
              out.unshift ta_message(msg)
            end
            if transfer.user_failed?
              out.unshift ta_message(FAIL_MSG)
            else
              out << fail_transfer_button(transfer)
            end
            if transfer.recipient_completed?
              msg = "#{name} claims success. Click 'OK' if you aggree"
              out.unshift ta_message(msg)
            end
            if transfer.user_completed?
              out.unshift ta_message(COMPLETE_MSG)
            else
              out << ok_transfer_button(transfer)
            end
          end

        end
        safe_join out
      end
    end
  end
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer||Transfer.new) do |form| %>
  <%= edit_fields form do %>
    <%= transfer_edit_fields form %>
  <% end %>
<% end %>

app/views/transfers/_form2.html.erb
<%= form_for(@user.transfers.build) do |form| %>
  <%= edit_fields form, :label=>"Send Money" do %>
    <%=transfer_edit_fields form %>
  <% end %>
<% end %>

app/views/transfers/_form3.html.erb
<%= form_for(@user.transfers.build) do |form| %>
  <%= edit_fields form, :label=>"Send Money" do %>
    <%=transfer_edit_fields form, :fixed_recipient=>true %>
  <% end %>
<% end %>

app/views/transfers/_list.html.erb
<%@transfers.each do |transfer| %>
  <%= render :partial=>"transfers/show", :locals=>{:transfer=>transfer} %>
<% end %>
<%= render "comments/modal" %>

app/views/transfers/_send_modal.html.erb
<div class="modal fade" id="send_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidd
en="true">&times;</span><span class="sr-only">Close</span></button>
	<div class="row">
	  <div class="col-sm-10 col-sm-offset-1">
	    <%= render "transfers/form3" %>
	  </div>
	</div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/transfers/_show.html.erb
<% color = transfer_color transfer %>
<div class="transfer <%= color %>" id="transfer_<%=transfer.id%>">
  <div class=clearfix>
    <div class="pull-left avatar">
      <% other = transfer.other_user(@current_user) %>
      <%= link_to show_avatar(other, :thumb), other %>
    </div>
    <div class="content">
      <div>
	<div>
	  <div class="pull-right amount">
	    <%= number_to_currency(transfer.amount) %>
	    <% if /^dashboard/ =~ params[:action] %>
	      <div>
		<%= dashboard_close_button transfer %>
	      </div>
	    <% end %>
	  </div>
	  <div>
	    <% if transfer.is_request? %>
	      Request
	    <% end %>
	    <% if transfer.user_id == session[:user_id] %>
	      To: <%= transfer.recipient.full_name %>
	    <% else %>
	      From: <%= transfer.user.full_name %>
	    <% end %>
	  </div>
	  <div>
	    <%= transfer.created_at_tz.strftime "%m/%d/%y %I:%M%p"%>
	  </div>
	  <div>
	    <%= transfer.message %>
	  </div>
	  <% if transfer.image.exists?  %>
	    <div>
	      <%= image_tag transfer.image.url(:medium) %>
	    </div>
	  <% end %>
	  <%= transfer_actions transfer %>
	</div>
      </div>
      <%= render(:partial=>"comments/list",
		 :locals=>{:comments=>transfer.comments})%>
    </div>
  </div>
</div>

app/views/transfers/edit.html.erb
<h1>Editing transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<h1>Listing transfers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Recipient</th>
      <th>Amount cents</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.user_id %></td>
        <td><%= transfer.recipient_id %></td>
        <td><%= transfer.amount_cents %></td>
        <td><%= transfer.note %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/off_dashboard.js.erb
tgt = $("#transfer_<%=@transfer.id%>")
tgt.fadeOut(1000, function(){tgt.remove()})

app/views/transfers/recent.html.erb
<h1>Recent Activity</h1>
<div class='row'>
<div class='row'>
<%= render :partial=>"list"%>
</div>
</div>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transfer.user_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @transfer.recipient_id %>
</p>

<p>
  <strong>Amount cents:</strong>
  <%= @transfer.amount_cents %>
</p>

<p>
  <strong>Note:</strong>
  <%= @transfer.note %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/update.js.erb
<% transfer =
    render :partial=>"show",:locals=>{:transfer=>@transfer} %>
content = $("<%=escape_javascript(transfer)%>")

id = content.attr("id");
$("#"+id).replaceWith(content);